language: node_js
dist: trusty
sudo: false
node_js:
  - '9'
  - '8'
  - '6'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - npm install

script:
  - npm test
